# -*- coding: utf-8 -*-
"""
PI E-727 + P-562.3CD — scanner motion hardware module
======================================================

Handles connection, motion and waveform scan commands only.
Does NOT implement ScanningProbeInterface and knows nothing about photon
counting -- combine with PIE710CounterInterfuse (via a photon counter) to
get a full ScanningProbeInterface, exactly like PIE710Scanner.

Implements the SAME abstract interface as PIE710Scanner
(PIE710ScannerInterface, imported from pi_e710_scanning_probe.py) so this
module is a drop-in replacement behind the existing PIE710CounterInterfuse
-- no changes needed to that interfuse's Connector wiring.

VERIFICATION STATUS
---------------------
CONFIDENT, standard across the PI GCS2 controller family: connection,
identification, servo on/off, MOV/MVR/qPOS, qONT/IsMoving, HLT/STP,
qTMN/qTMX, VEL/qVEL.

Wave/trigger logic (WAV_LIN, WSL, WGC, WGO, CTO) is ported directly from a
proven, working MATLAB implementation (ClassPiezoE727.m, in production use
on this exact controller/stage) rather than from the GCS command reference
alone. Confirmed on real hardware, in this order of discovery:

  1. All wave/trigger calls use the COMPILED per-command DLL functions
     (PI_WAV_LIN, PI_WSL, PI_WGC, PI_WGO, PI_CTO, ...) with real typed
     arguments, confirmed against the actual PI_GCS2_DLL.h header -- NOT
     the generic ASCII string channel (PI_GcsCommandset).

  2. The per-line trigger uses GCS TriggerMode 0 ("Position Distance"):
     one physical trigger pulse per pixel step, generated by the
     controller directly from real axis position (CTOPam 2=Axis,
     3=TriggerMode, 1=TriggerStep, 8=StartThreshold, 9=StopThreshold).
     The counting side (NIXSeriesCounter.arm_position_trigger()/
     read_position_trigger()) hardware-counts EVERY one of these pulses
     via a dedicated counter's CI count-edges channel, not just the
     first -- see that module's docstring for the acquisition model,
     including its EXPECTATION-BASED EDGE MATCHING, which is the actual
     fix for spurious extra real trigger edges at fine step sizes (see
     "MINIMUM TRIGGER STEP -- REMOVED" below for why this module no
     longer tries to prevent that condition pre-emptively).

  3. The waveform is a SINGLE ONE-WAY ramp per line, NOT a forward+
     backward triangle. WGO(...,0) explicitly STOPS the generator after
     one pass -- the stage does NOT return to its start position
     automatically. retrigger_line() is therefore a full repeat of
     start_scan()'s work (re-move + reprogram + retrigger), using the
     axis/positions/t_pixel cached from the most recent start_scan()
     call -- there is no cheaper path given how this hardware/algorithm
     actually works.

  4. TRIGGER-DISABLE ORDERING (real bug, fixed): scan_axis() must disable
     triggering (CTO param 8 -> disable_threshold) BEFORE moving to the
     new line's wave_offset, exactly matching the proven MATLAB
     ScanLine()'s own call order. Issuing the repositioning move first
     and only disabling triggering afterward leaves the PREVIOUS line's
     trigger thresholds fully armed while that move travels through a
     wide range of real positions -- generating real, physical extra
     trigger pulses that get counted as if they belonged to the next
     line.

  5. WAVE_OFFSET CLAMP (real bug, fixed): the padded-range pre-MOV check
     tolerates 1e-6 um of float noise around an exact travel-limit
     boundary -- but that tolerance only gates the CHECK; the literal
     wave_offset value must be clamped to [travel_min, travel_max] before
     being used by move_absolute()/wave_lin(), since real PI firmware
     enforces its travel limit with zero tolerance of its own.

AUTOMATIC SPEED-UP/SLOW-DOWN PADDING
----------------------------------------
Every scan line needs some amount of speed-up ramp before, and slow-down
ramp after, the real triggered region, so that the stage is already at
(or smoothly decelerating from) full scanning velocity while triggering
is active -- see "SCAN RANGE VS. PADDING" below for why this is a real,
physical requirement, not a tunable safety margin. This module computes
the padding needed for EVERY scan automatically, from two physically
named, independently-motivated limits -- there is no user-facing "ratio"
knob to hand-tune per scan:

  max_acceleration_um_s2 (ConfigOption, default 3000.0):
      The stage's real acceleration limit. A scan whose combination of
      span, resolution, and frequency would otherwise demand ramping up
      to scanning velocity faster than this gets MORE padding
      (proportionally more speed-up/slow-down time) automatically, so
      the implied average acceleration during that ramp never exceeds
      this value. Calibrated from a real hardware measurement: a scan
      spanning 120 um (40 to 160 um) at 100 points and 300 Hz was found
      to require a manually-tuned padding fraction equivalent to
      accelerating at ~3240 um/s^2 as the boundary of reliable
      triggering; 3000 um/s^2 keeps a small margin below that measured
      boundary. Treat this the same way as any hardware calibration
      constant in this file -- a real measurement on THIS stage/
      controller, not a PI-specified spec -- revisit if scans still show
      edge-count mismatches at the current default.

  min_speedup_time_s (ConfigOption, default 0.005):
      A floor under how little padding time a scan can ever be given,
      REGARDLESS of how slow/gentle it is. Exists specifically because a
      scan with NO speed-up ramp at all (the old lin_pts_ratio=1.0
      "padding off" case) was observed on real hardware to sometimes
      produce ZERO real trigger edges for an entire line -- the real
      servo response has following error/lag right at motion start with
      no ramp to smooth it, and the real position may never cleanly
      cross the trigger threshold at all. This floor guarantees every
      scan gets at least this much speed-up/slow-down time, even a very
      slow scan that the acceleration limit alone would otherwise let
      run with almost no padding at all.

      IMPORTANT: this is the reason padding cannot simply be removed now
      that NIXSeriesCounter.read_position_trigger() gained expectation-
      based edge matching (see that module's docstring). That change
      fixes a DIFFERENT failure mode -- real, genuine EXTRA trigger
      edges getting matched/discarded correctly -- but it can only work
      with edges that actually exist. A scan with no padding at all can
      produce ZERO real edges, and no downstream matching logic can
      recover a signal that was never generated. Padding therefore stays
      a real, physical requirement of this technique, independent of
      anything done on the counting/matching side.

      NOT CALIBRATED against real hardware the way max_acceleration_um_s2
      is -- we only know that a ZERO-length ramp can fail; we do not have
      a real measurement of the true minimum ramp time this stage needs.
      0.005 s (5 ms) is a conservative starting default, not a confirmed
      hardware constant. If you ever see edge-count mismatches
      SPECIFICALLY on slow/low-resolution scans (where this floor, not
      the acceleration limit, is the binding constraint), raise this
      value and re-test; if you confirm it can be lowered without
      trigger issues, that is useful data for tightening the default.

For a given scan (t_pixel, n_points, amp_true), the padding fraction
actually used is derived as follows. The linear (triggered) region's
duration is always exactly T = t_pixel * n_points, independent of how
much padding is applied (padding only ever adds MORE time before/after
this fixed-duration region, never touches per-pixel dwell time
integrity). From T, two independent upper bounds on the "fraction of
total line time spent in the linear region" (called ratio internally,
purely as an implementation detail of the WAV_LIN point-count math --
never exposed to a caller) are computed:

    ratio_max_accel   = (T^2 * a_max) / (T^2 * a_max + 2 * amp_true)
    ratio_max_speedup = T / (T + 2 * min_speedup_time_s)

and the LOWER (more conservative -- i.e. more total padding) of the two
is the one actually used for that scan. Setting either ConfigOption to
None or a non-positive value disables that specific constraint; if BOTH
are disabled, no padding is applied at all (ratio=1.0, reproducing the
original, unprotected "padding off" behavior -- entirely at the caller's
own risk, matching the failure mode described above).

SCAN RANGE VS. PADDING
--------------------------
Padding overshoots the commanded waveform beyond [start, stop] on both
sides, to give the stage room to accelerate up to scanning speed before
entering the real, triggered region (and decelerate after leaving it).
The padding needed on each side scales with the scan span:

    overshoot_per_side = amp_true * (1 - ratio) / (2 * ratio)

This is a real, physical requirement of the technique -- requesting a
scan spanning (close to) an axis' FULL real travel range, with padding
applied, will overshoot past the real travel limits and fail
scan_axis()'s pre-MOV range check (with a clear error) rather than
silently doing something unsafe.

get_scan_safe_range(axis, t_pixel, n_points) computes, in closed form,
the largest sub-range of an axis' real travel range that is guaranteed to
remain within real travel limits after padding is applied, for a SPECIFIC
scan's t_pixel/n_points (using the axis' full travel span as the
worst-case amplitude for that specific scan's implied padding
requirement). Passing the real t_pixel/n_points of the scan being
planned (as PIE710CounterInterfuse's configure_scan() now does) is what
keeps this self-consistent with what scan_axis() will actually do for
that exact request -- calling it without real parameters falls back to
NOT narrowing the range at all (logs a warning), since there is no longer
a fixed, parameter-independent padding fraction to assume.

PIE710CounterInterfuse uses this (via getattr, since PIE710Scanner has no
padding concept and therefore no need for this method) to clamp actual
scan requests into a range that fits after padding, logging a clear
warning when it does so. Only move_absolute()/get_position()/etc.
(ordinary, non-scanning motion) use the full real x_range/y_range/z_range;
axis.position bounds reported to Qudi are ALWAYS the true, full travel
range (never narrowed), since qudi's own scanning_probe_logic and
scanning_optimize_logic both reuse those bounds for ordinary absolute-
position validation completely independent of scanning.

MINIMUM TRIGGER STEP -- REMOVED
------------------------------------
An earlier version of this module added a min_trig_step_um ConfigOption
and a get_max_resolution_for_span() method, specifically to pre-emptively
CAP scan resolution so that the real per-pixel trigger step never got
"too small," based on real hardware measurements showing that fine steps
could produce EXTRA, spurious real trigger edges (confirmed via gap-
histogram analysis to be genuine electrical transitions, not a software
artifact -- root physical cause never conclusively isolated to one
mechanism).

That mechanism has been REMOVED. The problem it existed to prevent --
real, extra trigger edges beyond n_pixels + 1 -- is now handled
correctly downstream, in NIXSeriesCounter.read_position_trigger(), via
EXPECTATION-BASED EDGE MATCHING (see that module's docstring): every
real edge detected is matched against where a pixel boundary is
EXPECTED to be (from the scan's own real t_pixel), and anything extra is
discarded. This works correctly regardless of how many spurious edges
occur, without needing to guess a safe minimum step size in advance, and
without narrowing scan resolution pre-emptively. Pre-emptively capping
resolution is therefore no longer necessary, and no longer done here.

This does NOT change anything about the padding requirements above
(max_acceleration_um_s2, min_speedup_time_s) or the scan-range narrowing
that follows from them -- those protect against a different, still-real
failure mode (ZERO real trigger edges when there is no ramp at all),
which no downstream edge-matching logic can recover from, since there is
no signal to match against. See min_speedup_time_s's docstring above for
the direct statement of why these two fixes are independent.

STILL NOT INDEPENDENTLY VERIFIED ON THIS SPECIFIC UNIT: whether the
constant-acceleration ramp approximation underlying max_acceleration_um_s2
is a good match to PI's real internal speed-up curve shape (likely an
S-curve or similar easing, not literally constant acceleration), and the
real minimum speed-up time this stage needs (min_speedup_time_s's actual
calibrated value). Real hardware gap-timing measurements (see
NIXSeriesCounter's docstring) additionally showed the "linear" region is
not perfectly constant-velocity -- small (few-percent) systematic
deviations were measured, in different shapes at different scan
geometries. Treat max_acceleration_um_s2/min_speedup_time_s as useful,
conservative TUNING KNOBS confirmed to correctly predict the DIRECTION of
the real effect, not as first-principles-exact models of this
controller's real dynamics.

CRITICAL CROSS-FILE COUPLING -- RESOLVED
-------------------------------------------
An earlier version of this module's docstring warned that
NIXSeriesCounter's clock-based arm()/read() hardcodes a sample rate
(_PI_SAMP_RATE) that must match this controller's wave_generator_rate_hz.
That coupling does not apply when this scanner is used with
NIXSeriesCounter's arm_position_trigger()/read_position_trigger() methods
(selected via PIE710CounterInterfuse's counter_trigger_mode:
'position_distance' config option) -- that acquisition path has no
notion of a fixed scan clock rate at all; it hardware-counts real trigger
edges directly. Confirmed on real hardware for this E-727 (via
SPA? 1 0x0E000200 = 50 us servo cycle, WTR? = 1 cycle/point, and
independently confirmed by the proven MATLAB code's own SampRate = 20e3
property) that the true wave generator rate is 20000.0 Hz.

YAML configuration:
    hardware:
        my_pi_e727_scanner:
            module.Class: 'hardware.pi_e727_scanning_probe.PIE727Scanner'
            options:
                dll_path:   'C:/Users/diamondx/Documents/PIDriverThings/API/PI_GCS2_DLL_x64.dll'
                usb_serial: ''
                axis_ids:   ['1', '2', '3']
                x_range: [0.0, 200.0]
                y_range: [0.0, 200.0]
                z_range: [0.0, 200.0]
                trigger_output_id: 1
                wave_generator_rate_hz: 20000.0   # confirmed -- see module docstring
                max_acceleration_um_s2: 3000.0    # calibrated from real hardware -- see module docstring
                min_speedup_time_s: 0.005         # conservative, UNCALIBRATED default -- see module docstring
"""

import ctypes
import os
import threading
import time
from typing import Dict, List, Optional, Tuple

import numpy as np

from qudi.core.configoption import ConfigOption

from .pi_e710_scanning_probe import PIE710ScannerInterface


# ══════════════════════════════════════════════════════════════════════════════
#  PI GCS2 DLL WRAPPER  (PI_GCS2_DLL_x64.dll)
# ══════════════════════════════════════════════════════════════════════════════

class PIE727Error(Exception):
    def __init__(self, message: str, error_code: int = 0):
        super().__init__(message)
        self.error_code = error_code


class PIE727Controller:
    """
    ctypes wrapper for PI_GCS2_DLL_x64.dll, used with an E-727 digital
    piezo controller driving a P-562.3CD nanopositioning stage.

    See module docstring, "VERIFICATION STATUS", for what is confirmed
    against the real header vs. ported directly from the proven MATLAB
    implementation.
    """

    _SOFT_ERRORS = frozenset({0, 2, 5, 7, 8, 10})
    _BUF_SM = 256
    _BUF_MD = 1024

    def __init__(self, dll_path: str, use_windll: bool = False, logger=None):
        self._id: int = -1
        self._dll_path = dll_path
        self._registered: set = set()
        self._axes: List[str] = []
        self._travel_min: List[float] = []
        self._travel_max: List[float] = []

        # Optional logger (passed down from PIE727Scanner, which has
        # self.log via qudi's LogicBase/Base -- PIE727Controller itself is
        # a plain ctypes wrapper with no qudi logger of its own). If None,
        # padding-adjustment info messages are silently skipped.
        self._logger = logger

        self.wave_generator_rate_hz: Optional[float] = None
        self.servo_point_time_s: Optional[float] = None

        # See module docstring, "AUTOMATIC SPEED-UP/SLOW-DOWN PADDING".
        # Neither is a user-facing "ratio" -- both are physically named
        # limits combined automatically, per scan, in _effective_ratio().
        self.max_acceleration_um_s2: Optional[float] = None
        self.min_speedup_time_s: Optional[float] = None

        # Cached parameters from the most recent scan_axis() call, so
        # retrigger_line() can repeat the exact same line.
        self._last_scan_kwargs: Optional[dict] = None

        self._dll = self._load_dll(dll_path, use_windll)
        self._setup_signatures()

    @staticmethod
    def _load_dll(path: str, use_windll: bool) -> ctypes.CDLL:
        if not os.path.isfile(path):
            raise PIE727Error(f"DLL not found: '{path}'")
        try:
            return (ctypes.WinDLL if use_windll else ctypes.CDLL)(path)
        except OSError as exc:
            raise PIE727Error(f"Cannot load DLL: {exc}") from exc

    def _setup_signatures(self):
        d  = self._dll
        I  = ctypes.c_int
        D  = ctypes.c_double
        CP = ctypes.c_char_p
        PI = ctypes.POINTER(ctypes.c_int)
        PD = ctypes.POINTER(ctypes.c_double)

        def sig(name, rt, *at):
            try:
                fn = getattr(d, name)
                fn.restype = rt
                fn.argtypes = list(at)
                self._registered.add(name)
            except AttributeError:
                pass

        sig("PI_ConnectUSB",       I, CP)
        sig("PI_ConnectRS232",     I, I, I)
        sig("PI_IsConnected",      I, I)
        sig("PI_CloseConnection",  None, I)
        sig("PI_GetError",         I, I)
        sig("PI_TranslateError",   I, I, CP, I)

        sig("PI_qIDN",   I, I, CP, I)
        sig("PI_qVER",   I, I, CP, I)
        sig("PI_qSAI",   I, I, CP, I)

        sig("PI_SVO",       I, I, CP, PI)
        sig("PI_qSVO",      I, I, CP, PI)
        sig("PI_MOV",       I, I, CP, PD)
        sig("PI_MVR",       I, I, CP, PD)
        sig("PI_qPOS",      I, I, CP, PD)
        sig("PI_qONT",      I, I, CP, PI)
        sig("PI_IsMoving",  I, I, CP, PI)
        sig("PI_HLT",       I, I, CP)
        sig("PI_STP",       I, I)
        sig("PI_qTMN",      I, I, CP, PD)
        sig("PI_qTMX",      I, I, CP, PD)
        sig("PI_VEL",       I, I, CP, PD)
        sig("PI_qVEL",      I, I, CP, PD)

        sig("PI_qTIO", I, I, PI, PI)

        sig("PI_IsGeneratorRunning", I, I, PI, PI, I)
        sig("PI_WAV_LIN", I, I, I, I, I, I, I, D, D, I)
        sig("PI_qWAV",    I, I, PI, PI, PD, I)
        sig("PI_WGO",     I, I, PI, PI, I)
        sig("PI_qWGO",    I, I, PI, PI, I)
        sig("PI_WGC",     I, I, PI, PI, I)
        sig("PI_WSL",     I, I, PI, PI, I)
        sig("PI_WCL",     I, I, PI, I)
        sig("PI_WOS",     I, I, PI, PD, I)

        sig("PI_CTO",  I, I, PI, PI, PD, I)
        sig("PI_qCTO", I, I, PI, PI, PD, I)

    def _fn(self, name: str):
        if name not in self._registered:
            raise PIE727Error(
                f"'{name}' not exported by '{os.path.basename(self._dll_path)}'")
        return getattr(self._dll, name)

    def _require_connection(self):
        if self._id < 0:
            raise PIE727Error("Not connected.")

    def _check(self, result: int, fname: str):
        if not result:
            code = self._dll.PI_GetError(self._id) if self._id >= 0 else -1
            raise PIE727Error(
                f"'{fname}' failed -- error {code}: {self._translate(code)}", code)

    def _soft_check(self, result: int, fname: str) -> bool:
        if result:
            return True
        code = self._dll.PI_GetError(self._id) if self._id >= 0 else -1
        if code in self._SOFT_ERRORS:
            return False
        raise PIE727Error(
            f"'{fname}' failed -- error {code}: {self._translate(code)}", code)

    def _translate(self, code: int) -> str:
        if "PI_TranslateError" not in self._registered:
            return f"(PI_TranslateError not exported -- code {code} untranslated)"
        buf = ctypes.create_string_buffer(self._BUF_MD)
        try:
            self._fn("PI_TranslateError")(code, buf, self._BUF_MD)
        except Exception as exc:
            return f"(translation call failed for code {code}: {exc})"
        return buf.value.decode("ascii", errors="replace").strip()

    @staticmethod
    def _ax(axes) -> bytes:
        if isinstance(axes, bytes):
            return axes
        if isinstance(axes, (list, tuple)):
            return " ".join(str(a) for a in axes).encode("ascii")
        if isinstance(axes, str):
            return axes.encode("ascii")
        return b""

    @staticmethod
    def _nax(axes, fallback: int = 0) -> int:
        if isinstance(axes, (list, tuple)):
            return len(axes)
        b = PIE727Controller._ax(axes)
        return len(b.split()) if b else fallback

    @staticmethod
    def _darr(vals) -> ctypes.Array:
        v = list(vals)
        return (ctypes.c_double * len(v))(*v)

    @staticmethod
    def _iarr(vals) -> ctypes.Array:
        v = [int(x) for x in vals]
        return (ctypes.c_int * len(v))(*v)

    def _dbuf(self, n: int) -> ctypes.Array:
        return (ctypes.c_double * max(n, 1))()

    def _ibuf(self, n: int) -> ctypes.Array:
        return (ctypes.c_int * max(n, 1))()

    def clear_error(self):
        if self._id >= 0:
            self._dll.PI_GetError(self._id)

    @property
    def connected(self) -> bool:
        return self._id >= 0 and bool(self._dll.PI_IsConnected(self._id))

    @property
    def axes(self) -> List[str]:
        return list(self._axes)

    @property
    def travel_min(self) -> List[float]:
        return list(self._travel_min)

    @property
    def travel_max(self) -> List[float]:
        return list(self._travel_max)

    def connect_usb(self, description: str = "") -> int:
        _id = self._fn("PI_ConnectUSB")(description.encode("ascii"))
        if _id < 0:
            raise PIE727Error(f"USB connect failed (description='{description}')")
        self._id = _id
        return _id

    def connect_rs232(self, port_number: int, baud_rate: int = 115200) -> int:
        _id = self._fn("PI_ConnectRS232")(port_number, baud_rate)
        if _id < 0:
            raise PIE727Error(f"RS-232 connect failed (COM{port_number})")
        self._id = _id
        return _id

    def close_connection(self):
        if self._id >= 0:
            try:
                self._fn("PI_CloseConnection")(self._id)
            except Exception:
                pass
            self._id = -1

    def get_identification(self) -> str:
        self._require_connection()
        buf = ctypes.create_string_buffer(self._BUF_MD)
        self._check(self._fn("PI_qIDN")(self._id, buf, self._BUF_MD), "qIDN")
        return buf.value.decode("ascii", errors="replace").strip()

    def get_version(self) -> str:
        self._require_connection()
        buf = ctypes.create_string_buffer(self._BUF_MD)
        ok = self._soft_check(
            self._fn("PI_qVER")(self._id, buf, self._BUF_MD), "qVER")
        return (buf.value.decode("ascii", errors="replace").strip()
                if ok else "(not supported)")

    def get_axes(self) -> List[str]:
        self._require_connection()
        buf = ctypes.create_string_buffer(self._BUF_MD)
        ok = self._soft_check(
            self._fn("PI_qSAI")(self._id, buf, self._BUF_MD), "qSAI")
        if not ok:
            return ['1', '2', '3']
        raw = buf.value.decode("ascii", errors="replace").strip()
        axes = [line.strip() for line in raw.splitlines() if line.strip()]
        return axes if axes else ['1', '2', '3']

    def get_digital_io_counts(self) -> Tuple[int, int]:
        self._require_connection()
        n_in, n_out = ctypes.c_int(0), ctypes.c_int(0)
        self._check(
            self._fn("PI_qTIO")(self._id, ctypes.byref(n_in), ctypes.byref(n_out)),
            "qTIO")
        return n_in.value, n_out.value

    def set_servo(self, axes, states: List[bool]):
        self._require_connection()
        self._check(
            self._fn("PI_SVO")(self._id, self._ax(axes), self._iarr(states)),
            "SVO")

    def get_servo(self, axes) -> List[bool]:
        self._require_connection()
        n = self._nax(axes, len(self._axes))
        arr = self._ibuf(n)
        self._check(self._fn("PI_qSVO")(self._id, self._ax(axes), arr), "qSVO")
        return [bool(arr[i]) for i in range(n)]

    def get_position(self, axes) -> List[float]:
        self._require_connection()
        n = self._nax(axes, len(self._axes))
        arr = self._dbuf(n)
        self._check(self._fn("PI_qPOS")(self._id, self._ax(axes), arr), "qPOS")
        return [arr[i] for i in range(n)]

    def move_absolute(self, axes, positions: List[float]):
        self._require_connection()
        self._check(
            self._fn("PI_MOV")(self._id, self._ax(axes), self._darr(positions)),
            "MOV")

    def move_relative(self, axes, steps: List[float]):
        self._require_connection()
        self._check(
            self._fn("PI_MVR")(self._id, self._ax(axes), self._darr(steps)),
            "MVR")

    def is_moving(self, axes) -> List[bool]:
        self._require_connection()
        n = self._nax(axes, len(self._axes))
        arr = self._ibuf(n)
        self._check(
            self._fn("PI_IsMoving")(self._id, self._ax(axes), arr), "IsMoving")
        return [bool(arr[i]) for i in range(n)]

    def is_on_target(self, axes) -> List[bool]:
        self._require_connection()
        n = self._nax(axes, len(self._axes))
        arr = self._ibuf(n)
        self._check(
            self._fn("PI_qONT")(self._id, self._ax(axes), arr), "qONT")
        return [bool(arr[i]) for i in range(n)]

    def halt(self, axes):
        self._require_connection()
        self._check(self._fn("PI_HLT")(self._id, self._ax(axes)), "HLT")

    def stop_all(self):
        self._require_connection()
        self._check(self._fn("PI_STP")(self._id), "STP")

    def wait_for_motion(
        self, axes, poll_interval: float = 0.05,
        timeout: float = 60.0, settle_check: bool = True,
    ):
        deadline = time.monotonic() + timeout
        while any(self.is_moving(axes)):
            if time.monotonic() > deadline:
                raise PIE727Error(f"Timeout waiting for motion on '{axes}'")
            time.sleep(poll_interval)
        if settle_check:
            settle_deadline = time.monotonic() + min(timeout * 0.25, 5.0)
            while not all(self.is_on_target(axes)):
                if time.monotonic() > settle_deadline:
                    break
                time.sleep(poll_interval)

    def get_min_travel(self, axes) -> List[float]:
        self._require_connection()
        n = self._nax(axes, len(self._axes))
        arr = self._dbuf(n)
        self._check(self._fn("PI_qTMN")(self._id, self._ax(axes), arr), "qTMN")
        return [arr[i] for i in range(n)]

    def get_max_travel(self, axes) -> List[float]:
        self._require_connection()
        n = self._nax(axes, len(self._axes))
        arr = self._dbuf(n)
        self._check(self._fn("PI_qTMX")(self._id, self._ax(axes), arr), "qTMX")
        return [arr[i] for i in range(n)]

    def set_velocity(self, axes, velocities: List[float]):
        self._require_connection()
        self._check(
            self._fn("PI_VEL")(self._id, self._ax(axes), self._darr(velocities)),
            "VEL")

    def wave_clear(self, wave_table_ids: List[int]):
        self._require_connection()
        arr = self._iarr(wave_table_ids)
        self._check(
            self._fn("PI_WCL")(self._id, arr, len(wave_table_ids)), "WCL")

    def wave_lin(
        self, wave_table_id: int, offset_first_point: int,
        n_points: int, add_append_wave: int,
        n_speedupdown_points: int, amplitude: float, offset: float,
        segment_length: int,
    ):
        """
        PI_WAV_LIN(ID, iWaveTableId, iOffsetOfFirstPointInWaveTable,
        iNumberOfPoints, iAddAppendWave, iNumberOfSpeedUpDownPointsInWave,
        dAmplitudeOfWave, dOffsetOfWave, iSegmentLength)
        """
        self._require_connection()
        self._check(
            self._fn("PI_WAV_LIN")(
                self._id, wave_table_id, offset_first_point, n_points,
                add_append_wave, n_speedupdown_points,
                ctypes.c_double(amplitude), ctypes.c_double(offset),
                segment_length),
            "WAV_LIN")

    def wave_select(self, wave_gen_ids: List[int], wave_table_ids: List[int]):
        self._require_connection()
        assert len(wave_gen_ids) == len(wave_table_ids)
        self._check(
            self._fn("PI_WSL")(
                self._id, self._iarr(wave_gen_ids), self._iarr(wave_table_ids),
                len(wave_gen_ids)),
            "WSL")

    def wave_set_cycles(self, wave_gen_ids: List[int], cycles: List[int]):
        self._require_connection()
        assert len(wave_gen_ids) == len(cycles)
        self._check(
            self._fn("PI_WGC")(
                self._id, self._iarr(wave_gen_ids), self._iarr(cycles),
                len(wave_gen_ids)),
            "WGC")

    def wave_set_offset(self, wave_gen_ids: List[int], offsets: List[float]):
        self._require_connection()
        assert len(wave_gen_ids) == len(offsets)
        self._check(
            self._fn("PI_WOS")(
                self._id, self._iarr(wave_gen_ids), self._darr(offsets),
                len(wave_gen_ids)),
            "WOS")

    def wave_start_stop(self, wave_gen_ids: List[int], start_modes: List[int]):
        """
        PI_WGO(ID, piWaveGeneratorIdsArray, iStartModArray, iArraySize).
        start_modes: 1 = start, 0 = stop.
        """
        self._require_connection()
        assert len(wave_gen_ids) == len(start_modes)
        self._check(
            self._fn("PI_WGO")(
                self._id, self._iarr(wave_gen_ids), self._iarr(start_modes),
                len(wave_gen_ids)),
            "WGO")

    def is_wave_generator_running(self, wave_gen_ids: List[int]) -> List[bool]:
        self._require_connection()
        arr = self._iarr(wave_gen_ids)
        out = self._ibuf(len(wave_gen_ids))
        self._check(
            self._fn("PI_IsGeneratorRunning")(
                self._id, arr, out, len(wave_gen_ids)),
            "IsGeneratorRunning")
        return [bool(out[i]) for i in range(len(wave_gen_ids))]

    def set_trigger_param(self, trig_out_id: int, cto_param: int, value: float):
        self._require_connection()
        self._check(
            self._fn("PI_CTO")(
                self._id,
                self._iarr([trig_out_id]),
                self._iarr([cto_param]),
                self._darr([value]),
                1),
            f"CTO (param={cto_param}, value={value})")

    def get_trigger_param(self, trig_out_id: int, cto_param: int) -> float:
        self._require_connection()
        out = self._dbuf(1)
        self._check(
            self._fn("PI_qCTO")(
                self._id, self._iarr([trig_out_id]), self._iarr([cto_param]),
                out, 1),
            "qCTO")
        return out[0]

    def configure_position_distance_trigger(
        self, trigger_output_id: int, axis_num: int,
        trig_step: float, trig_start: float, trig_stop: float,
        disable_threshold: float,
    ):
        """
        Configure trigger_output_id for GCS TriggerMode 0 ("Position
        Distance"): one physical trigger pulse per trig_step of real
        motion along axis_num, only while position is within
        [trig_start, trig_stop]. Ported directly from the proven MATLAB
        ScanLine sequence.
        """
        self.set_trigger_param(trigger_output_id, 8, disable_threshold)
        self.set_trigger_param(trigger_output_id, 2, axis_num)
        self.set_trigger_param(trigger_output_id, 3, 0)
        self.set_trigger_param(trigger_output_id, 1, trig_step)
        self.set_trigger_param(trigger_output_id, 8, trig_start)
        self.set_trigger_param(trigger_output_id, 9, trig_stop)

    # ── Automatic padding computation ──────────────────────────────────────────

    def _effective_ratio(self, t_pixel: float, n_points: int, amp_true: float) -> float:
        """
        See module docstring, "AUTOMATIC SPEED-UP/SLOW-DOWN PADDING", for
        the full derivation. Combines max_acceleration_um_s2 and
        min_speedup_time_s into the internal "fraction of line time spent
        in the linear region" needed for THIS specific scan's WAV_LIN
        point-count math -- this value is never exposed to a caller as a
        tunable setting; it is fully derived, per scan, from the two
        named, physical ConfigOptions above.
        """
        T = t_pixel * n_points
        if T <= 0 or amp_true == 0:
            return 1.0

        candidates = []
        reasons = []

        a_max = self.max_acceleration_um_s2
        if a_max is not None and a_max > 0:
            r = (T * T * a_max) / (T * T * a_max + 2.0 * abs(amp_true))
            candidates.append(min(r, 1.0))
            reasons.append(('max_acceleration_um_s2', a_max, r))

        min_su = self.min_speedup_time_s
        if min_su is not None and min_su > 0:
            r = T / (T + 2.0 * min_su)
            candidates.append(min(r, 1.0))
            reasons.append(('min_speedup_time_s', min_su, r))

        if not candidates:
            return 1.0

        ratio = min(candidates)

        if ratio < 1.0 and self._logger is not None:
            binding = min(reasons, key=lambda x: x[2])
            self._logger.debug(
                f"scan_axis: applying automatic padding (ratio={ratio:.4f}) "
                f"for span={amp_true:.3f} um, n_points={n_points}, "
                f"t_pixel={t_pixel*1e3:.4f} ms -- binding constraint: "
                f"{binding[0]}={binding[1]}"
            )

        return ratio

    # ── High-level single-axis line scan (ported from proven MATLAB ScanLine) ─

    def scan_axis(
        self, axis_num: int, positions, t_pixel: float,
        trigger_output_id: int, wave_generator_rate_hz: float,
        disable_threshold: float,
    ) -> float:
        """
        Configure and run a single-axis line scan. See module docstring
        for the full description of the ported MATLAB algorithm and the
        automatic padding computation (_effective_ratio()).
        """
        self._require_connection()
        n_points = len(positions)
        start, stop = positions[0], positions[-1]
        amp_true = stop - start

        ratio = self._effective_ratio(t_pixel, n_points, amp_true)
        servo_pt = 1.0 / wave_generator_rate_hz
        line_time = t_pixel * n_points / min(ratio, 1.0)

        if ratio >= 1.0:
            # Both max_acceleration_um_s2 and min_speedup_time_s disabled
            # (None/<=0) -- no padding at all. Reproduces the original,
            # unprotected behavior -- see module docstring for the known
            # real-hardware risk (zero trigger edges) of this mode.
            wave_offset = start
            amp_padded = amp_true
            n_speedupdown = 0
            linear_region_len = round(line_time / servo_pt)
        else:
            perc_over = ratio / ((1.0 - ratio) / 2.0)
            wave_offset = start - amp_true / perc_over
            amp_padded = amp_true / ratio
            linear_region_len = round(line_time * ratio / servo_pt)
            n_speedupdown = round(line_time * (1.0 - ratio) / servo_pt / 2.0)

        n_wave_points = linear_region_len + 2 * n_speedupdown
        segment_length = n_wave_points

        # Validate the padded range against real travel limits BEFORE
        # issuing MOV. Tolerance clears IEEE double-precision rounding
        # noise in the padding arithmetic above.
        travel_min = self.get_min_travel([str(axis_num)])[0]
        travel_max = self.get_max_travel([str(axis_num)])[0]
        padded_low  = wave_offset
        padded_high = wave_offset + amp_padded
        _tol = 1e-6
        if padded_low < travel_min - _tol or padded_high > travel_max + _tol:
            raise PIE727Error(
                f"scan_axis: padded scan range [{padded_low:.4f}, "
                f"{padded_high:.4f}] um (requested [{start:.4f}, "
                f"{stop:.4f}] um"
                + ("" if ratio >= 1.0 else
                   f" + automatic speed-up/slow-down padding, effective "
                   f"ratio={ratio:.4f}")
                + f") exceeds axis {axis_num}'s real travel range "
                f"[{travel_min:.4f}, {travel_max:.4f}] um."
            )

        # The tolerance above only gates the sanity CHECK -- it does not
        # change the value actually sent to move_absolute()/wave_lin().
        # Real PI firmware enforces its travel limit with zero tolerance
        # of its own, so clamp here, AFTER the sanity check, to snap any
        # remaining float noise back onto the real boundary.
        wave_offset = float(np.clip(wave_offset, travel_min, travel_max))

        # Disable triggering BEFORE moving to the new line's wave_offset
        # -- matches the proven MATLAB ScanLine's ordering. See module
        # docstring, item 4.
        self.set_trigger_param(trigger_output_id, 8, disable_threshold)

        self.move_absolute([str(axis_num)], [wave_offset])
        self.wait_for_motion([str(axis_num)], timeout=30.0)

        self.wave_clear([axis_num])
        self.wave_set_cycles([axis_num], [1])
        self.wave_lin(
            wave_table_id=axis_num, offset_first_point=0,
            n_points=n_wave_points, add_append_wave=0,
            n_speedupdown_points=n_speedupdown,
            amplitude=amp_padded, offset=wave_offset,
            segment_length=segment_length,
        )
        self.wave_select([axis_num], [axis_num])

        trig_step = amp_true / n_points
        trig_start = start
        trig_stop = trig_start + amp_true + trig_step * 0.5
        self.configure_position_distance_trigger(
            trigger_output_id=trigger_output_id, axis_num=axis_num,
            trig_step=trig_step, trig_start=trig_start, trig_stop=trig_stop,
            disable_threshold=disable_threshold,
        )

        self.wave_set_offset([axis_num], [0.0])
        self.wave_start_stop([axis_num], [1])

        return segment_length * servo_pt * 1.1

    def retrigger_line(self) -> float:
        """
        Re-run the most recently configured line scan from scratch --
        see module docstring, item 3, for why this must be a full repeat
        (move + reprogram + retrigger), not a bare WGO restart. Uses the
        SAME cached t_pixel/positions as the original call, so the
        automatic padding computation is recomputed identically every
        time from those same cached inputs.
        """
        if self._last_scan_kwargs is None:
            raise PIE727Error(
                "retrigger_line() called with no prior scan_axis() call.")
        return self.scan_axis(**self._last_scan_kwargs)

    def __enter__(self):
        return self

    def __exit__(self, *_):
        self.close_connection()

    def __del__(self):
        try:
            self.close_connection()
        except Exception:
            pass


# ══════════════════════════════════════════════════════════════════════════════
#  CONCRETE HARDWARE MODULE — PIE727Scanner
# ══════════════════════════════════════════════════════════════════════════════

class PIE727Scanner(PIE710ScannerInterface):
    """
    PI E-727 + P-562.3CD Qudi hardware module — motion and waveform
    control only. Drop-in replacement for PIE710Scanner behind
    PIE710CounterInterfuse.

    See module docstring, "VERIFICATION STATUS", before trusting scan
    timing/trigger behavior further on real hardware.
    """

    _dll_path              = ConfigOption('dll_path', default="C:/PI/PI_GCS2_DLL_x64.dll")
    _usb_serial            = ConfigOption('usb_serial', default="")
    _axis_ids              = ConfigOption('axis_ids', default=['1', '2', '3'])
    _x_range               = ConfigOption('x_range', default=[0.0, 200.0])
    _y_range               = ConfigOption('y_range', default=[0.0, 200.0])
    _z_range               = ConfigOption('z_range', default=[0.0, 200.0])
    _trigger_output_id     = ConfigOption('trigger_output_id', default=1)
    _wave_generator_rate_hz = ConfigOption('wave_generator_rate_hz', default=20000.0)
    _max_acceleration_um_s2 = ConfigOption('max_acceleration_um_s2', default=3000.0)
    _min_speedup_time_s     = ConfigOption('min_speedup_time_s', default=0.005)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._ctrl: Optional[PIE727Controller] = None
        self._target_pos: Dict[str, float] = {'x': 0.0, 'y': 0.0, 'z': 0.0}
        self._axis_of: Dict[str, str] = {}
        self._active_scan_axis: Optional[str] = None

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    def on_activate(self) -> None:
        self._ctrl = None
        try:
            self._ctrl = PIE727Controller(self._dll_path, logger=self.log)
            self._ctrl.connect_usb(self._usb_serial)

            ids = list(self._axis_ids)
            if len(ids) < 3:
                raise PIE727Error(
                    f"axis_ids config must have 3 entries (x,y,z); got {ids}")
            self._axis_of = {'x': ids[0], 'y': ids[1], 'z': ids[2]}
            self._ctrl._axes = ids

            idn = self._ctrl.get_identification()
            self.log.info(f"PI E-727 connected: {idn}")

            self._ctrl.set_servo(ids, [True, True, True])
            time.sleep(0.1)

            mn = self._ctrl.get_min_travel(ids)
            mx = self._ctrl.get_max_travel(ids)
            self.log.info(
                f"Travel limits (from hardware): "
                f"{ids[0]}:[{mn[0]:.3f},{mx[0]:.3f}]  "
                f"{ids[1]}:[{mn[1]:.3f},{mx[1]:.3f}]  "
                f"{ids[2]}:[{mn[2]:.3f},{mx[2]:.3f}] um"
            )
            self._x_range = [mn[0], mx[0]]
            self._y_range = [mn[1], mx[1]]
            self._z_range = [mn[2], mx[2]]

            pos = self._ctrl.get_position(ids)
            self._target_pos = {'x': pos[0], 'y': pos[1], 'z': pos[2]}
            self.log.info(
                f"Position  x={pos[0]:.3f}  y={pos[1]:.3f}  z={pos[2]:.3f} um"
            )

            self._ctrl.wave_generator_rate_hz = float(self._wave_generator_rate_hz)
            self._ctrl.servo_point_time_s = 1.0 / float(self._wave_generator_rate_hz)
            self._ctrl.max_acceleration_um_s2 = (
                float(self._max_acceleration_um_s2)
                if self._max_acceleration_um_s2 is not None else None
            )
            self._ctrl.min_speedup_time_s = (
                float(self._min_speedup_time_s)
                if self._min_speedup_time_s is not None else None
            )

            self.log.info(
                f"Automatic scan padding active: "
                f"max_acceleration_um_s2={self._ctrl.max_acceleration_um_s2}  "
                f"min_speedup_time_s={self._ctrl.min_speedup_time_s}  "
                f"-- padding is computed fresh per scan; see module "
                f"docstring for what each limit protects against. "
                f"No minimum-trigger-step restriction is applied -- "
                f"spurious extra trigger edges at fine step sizes are "
                f"handled downstream by NIXSeriesCounter's expectation-"
                f"based edge matching."
            )
        except Exception as exc:
            if self._ctrl is not None:
                try:
                    self._ctrl.close_connection()
                except Exception:
                    pass
                self._ctrl = None
            self.log.exception(f"PI E-727 activation failed: {exc}")
            raise

    def on_deactivate(self) -> None:
        if self._ctrl is not None:
            try:
                self._ctrl.close_connection()
            except Exception as exc:
                self.log.warning(f"PI close_connection: {exc}")
            self._ctrl = None

    # ── Range properties (real hardware travel limits) ────────────────────────

    @property
    def x_range(self) -> List[float]:
        return list(self._x_range)

    @property
    def y_range(self) -> List[float]:
        return list(self._y_range)

    @property
    def z_range(self) -> List[float]:
        return list(self._z_range)

    # ── Scan-safe range (padding-aware) ────────────────────────────────────────

    def get_scan_safe_range(
        self, axis: str,
        t_pixel: Optional[float] = None, n_points: Optional[int] = None,
    ) -> List[float]:
        """
        Returns the sub-range of this axis' real travel range that is
        guaranteed to remain within real travel limits after scan_axis()
        applies its automatic padding, FOR A SCAN WITH THIS SPECIFIC
        t_pixel/n_points spanning up to the entire returned range.

        Pass the ACTUAL t_pixel/n_points of the scan being planned --
        PIE710CounterInterfuse does this at configure_scan() time. This
        is required for a self-consistent answer: since padding is
        computed per-scan (see module docstring, "AUTOMATIC SPEED-UP/
        SLOW-DOWN PADDING"), there is no single, parameter-independent
        padding fraction to assume.

        If t_pixel/n_points are omitted, this CANNOT compute a real
        margin and returns the full, real travel range UNCHANGED (logging
        a warning) -- i.e. it does not narrow anything rather than risk
        returning an inconsistent, falsely-optimistic answer.

        Does NOT affect move_absolute()/get_position()/etc. -- ordinary,
        non-scanning motion always uses the full real x_range/y_range/
        z_range; only scan-range clamping (in the interfuse) uses this.

        This range narrowing exists to keep padding overshoot within
        real travel limits (see module docstring, "SCAN RANGE VS.
        PADDING") -- it is unrelated to, and unaffected by, the removal
        of the old min_trig_step_um resolution cap (see module docstring,
        "MINIMUM TRIGGER STEP -- REMOVED").
        """
        full = {'x': self._x_range, 'y': self._y_range, 'z': self._z_range}[axis]
        lo, hi = full

        if t_pixel is None or n_points is None or self._ctrl is None:
            self.log.warning(
                f"get_scan_safe_range('{axis}') called without real scan "
                f"parameters (t_pixel/n_points) -- cannot compute a "
                f"self-consistent safe range; returning the full, "
                f"unclamped travel range [{lo:.4f}, {hi:.4f}] um."
            )
            return [lo, hi]

        amp_true = hi - lo
        ratio = self._ctrl._effective_ratio(t_pixel, n_points, amp_true)
        if ratio >= 1.0:
            margin = 0.0
        else:
            margin = amp_true * (1.0 - ratio) / 2.0

        return [round(lo + margin, 6), round(hi - margin, 6)]

    # ── Motion ────────────────────────────────────────────────────────────────

    def move_absolute(
        self, position: Dict[str, float], blocking: bool = False,
    ) -> Dict[str, float]:
        target = dict(self._target_pos)
        for ax, val in position.items():
            if ax in ('x', 'y', 'z'):
                target[ax] = float(val)
        target['x'] = float(np.clip(target['x'], *self._x_range))
        target['y'] = float(np.clip(target['y'], *self._y_range))
        target['z'] = float(np.clip(target['z'], *self._z_range))

        ids = [self._axis_of['x'], self._axis_of['y'], self._axis_of['z']]
        self._ctrl.move_absolute(ids, [target['x'], target['y'], target['z']])
        self._target_pos = target
        if blocking:
            self._ctrl.wait_for_motion(ids, timeout=60.0)
        return dict(self._target_pos)

    def move_relative(
        self, distance: Dict[str, float], blocking: bool = False,
    ) -> Dict[str, float]:
        current = self.get_target()
        new_pos = {ax: current[ax] + distance.get(ax, 0.0) for ax in ('x', 'y', 'z')}
        return self.move_absolute(new_pos, blocking=blocking)

    def get_target(self) -> Dict[str, float]:
        return dict(self._target_pos)

    def get_position(self) -> Dict[str, float]:
        try:
            ids = [self._axis_of['x'], self._axis_of['y'], self._axis_of['z']]
            pos = self._ctrl.get_position(ids)
            return {'x': pos[0], 'y': pos[1], 'z': pos[2]}
        except PIE727Error:
            return dict(self._target_pos)

    def sync_position(self) -> None:
        try:
            ids = [self._axis_of['x'], self._axis_of['y'], self._axis_of['z']]
            pos = self._ctrl.get_position(ids)
            self._target_pos = {'x': pos[0], 'y': pos[1], 'z': pos[2]}
        except PIE727Error as exc:
            self.log.warning(f"sync_position failed: {exc}")

    def halt(self) -> None:
        try:
            ids = [self._axis_of['x'], self._axis_of['y'], self._axis_of['z']]
            self._ctrl.halt(ids)
        except PIE727Error:
            pass

    def halt_generators(self) -> None:
        if self._active_scan_axis is not None:
            try:
                axis_num = int(self._axis_of[self._active_scan_axis])
                self._ctrl.wave_start_stop([axis_num], [0])
            except Exception:
                pass

    def reset(self) -> None:
        try:
            ids = [self._axis_of['x'], self._axis_of['y'], self._axis_of['z']]
            self._ctrl.set_servo(ids, [True, True, True])
            self.log.info("PI E-727 reset complete.")
        except PIE727Error as exc:
            self.log.error(f"PI E-727 reset failed: {exc}")

    # ── Scan commands ─────────────────────────────────────────────────────────

    def start_scan(
        self,
        axes:        Tuple[str, ...],
        positions:   Tuple[List[float], ...],
        t_pixel:     float,
        current_pos: Dict[str, float],
    ) -> float:
        if len(axes) != 1:
            raise NotImplementedError(
                "PIE727Scanner currently implements single-axis (1D fast-"
                "axis) line scans only. For 2D scanning, the interfuse's "
                "own line-by-line-via-retrigger_line() mechanism already "
                "covers this via repeated calls to this method + "
                "retrigger_line() per line."
            )

        axis = axes[0]
        axis_num = int(self._axis_of[axis])
        pos_array = positions[0]
        disable_threshold = max(self._x_range[1], self._y_range[1], self._z_range[1]) + 1.0

        scan_kwargs = dict(
            axis_num=axis_num, positions=pos_array, t_pixel=t_pixel,
            trigger_output_id=self._trigger_output_id,
            wave_generator_rate_hz=self._wave_generator_rate_hz,
            disable_threshold=disable_threshold,
        )
        duration_s = self._ctrl.scan_axis(**scan_kwargs)
        self._ctrl._last_scan_kwargs = scan_kwargs
        self._active_scan_axis = axis

        # Per module docstring, item 3: the stage is left at the END of
        # the ramp after the scan completes, NOT back at pos_array[0].
        self._target_pos[axis] = pos_array[-1]

        return duration_s

    def retrigger_line(self) -> float:
        duration_s = self._ctrl.retrigger_line()
        if self._active_scan_axis is not None:
            positions = self._ctrl._last_scan_kwargs['positions']
            self._target_pos[self._active_scan_axis] = positions[-1]
        return duration_s

    def wait_for_scan_complete(
        self,
        estimated_s:   float,
        stop_event:    Optional[threading.Event] = None,
        poll_interval: float = 0.25,
    ) -> bool:
        coarse_s = max(0.0, estimated_s * 0.80 - poll_interval)
        deadline = time.monotonic() + estimated_s * 3.0 + 10.0

        elapsed, chunk = 0.0, 0.1
        while elapsed < coarse_s:
            if stop_event and stop_event.is_set():
                return False
            time.sleep(chunk)
            elapsed += chunk

        axis_num = int(self._axis_of[self._active_scan_axis]) if self._active_scan_axis else None
        try:
            while time.monotonic() < deadline:
                if stop_event and stop_event.is_set():
                    return False
                if axis_num is not None and not self._ctrl.is_wave_generator_running([axis_num])[0]:
                    break
                time.sleep(poll_interval)
            else:
                self.log.warning("Scan completion timeout exceeded.")
        except Exception as exc:
            self.log.warning(f"Wave generator poll failed ({exc}); time-based fallback.")
            time.sleep(max(0.0, estimated_s - elapsed))

        # Per module docstring: the generator does NOT stop itself --
        # explicitly stop it now that the scan is done.
        if axis_num is not None:
            try:
                self._ctrl.wave_start_stop([axis_num], [0])
            except Exception as exc:
                self.log.warning(f"Failed to explicitly stop wave generator: {exc}")

        return True