# -*- coding: utf-8 -*-
"""
PI E-727 + P-562.3CD — scanner motion hardware module
======================================================

Handles connection, motion and waveform scan commands only.
Does NOT implement ScanningProbeInterface and knows nothing about photon
counting -- combine with PIE710CounterInterfuse (via a photon counter) to
get a full ScanningProbeInterface, exactly like PIE710Scanner.

Implements the SAME abstract interface as PIE710Scanner
(PIE710ScannerInterface, imported from pi_e710_scanning_probe.py) so this
module is a drop-in replacement behind the existing PIE710CounterInterfuse
-- no changes needed to that interfuse's Connector wiring.

VERIFICATION STATUS
---------------------
CONFIDENT, standard across the PI GCS2 controller family: connection,
identification, servo on/off, MOV/MVR/qPOS, qONT/IsMoving, HLT/STP,
qTMN/qTMX, VEL/qVEL.

Wave/trigger logic (WAV_LIN, WSL, WGC, WGO, CTO) is ported directly from a
proven, working MATLAB implementation (ClassPiezoE727.m, in production use
on this exact controller/stage) rather than from the GCS command reference
alone. Confirmed on real hardware, in this order of discovery:

  1. All wave/trigger calls use the COMPILED per-command DLL functions
     (PI_WAV_LIN, PI_WSL, PI_WGC, PI_WGO, PI_CTO, ...) with real typed
     arguments, confirmed against the actual PI_GCS2_DLL.h header -- NOT
     the generic ASCII string channel (PI_GcsCommandset).

  2. The per-line trigger uses GCS TriggerMode 0 ("Position Distance"):
     one physical trigger pulse per pixel step, generated by the
     controller directly from real axis position (CTOPam 2=Axis,
     3=TriggerMode, 1=TriggerStep, 8=StartThreshold, 9=StopThreshold).
     The counting side (NIXSeriesCounter.arm_position_trigger()/
     read_position_trigger()) hardware-counts EVERY one of these pulses
     via a dedicated counter's CI count-edges channel, not just the
     first -- see that module's docstring for the acquisition model.

  3. The waveform is a SINGLE ONE-WAY ramp per line, NOT a forward+
     backward triangle. WGO(...,0) explicitly STOPS the generator after
     one pass -- the stage does NOT return to its start position
     automatically. retrigger_line() is therefore a full repeat of
     start_scan()'s work (re-move + reprogram + retrigger), using the
     axis/positions/t_pixel cached from the most recent start_scan()
     call -- there is no cheaper path given how this hardware/algorithm
     actually works.

  4. TRIGGER-DISABLE ORDERING (real bug, fixed): scan_axis() must disable
     triggering (CTO param 8 -> disable_threshold) BEFORE moving to the
     new line's wave_offset, exactly matching the proven MATLAB
     ScanLine()'s own call order (CTO disable is its very first
     trigger-related call, issued before MOV). An earlier version of
     this method issued the repositioning move first and only disabled
     triggering afterward, leaving the PREVIOUS line's trigger
     thresholds fully armed while that move traveled through a wide
     range of real positions -- generating real, physical extra trigger
     pulses that got counted as if they belonged to the next line.
     Confirmed via hardware trace: a cluster of spurious edges with a
     smoothly-decelerating time signature appeared identically regardless
     of the new scan's own pixel count/geometry, which only makes sense
     if they were produced by the repositioning move using stale trigger
     config, not by the new line's own (correctly configured) triggering.

SCAN RANGE VS. lin_pts_ratio PADDING
--------------------------------------
When lin_pts_ratio < 1.0, scan_axis() pads the commanded waveform beyond
[start, stop] on both sides, to give the stage room to accelerate up to
scanning speed before entering the real, triggered region (and decelerate
after leaving it). The padding needed on each side scales with the scan
span:

    overshoot_per_side = amp_true * (1 - ratio) / (2 * ratio)

This is a real, physical requirement of the technique, not a tunable
safety margin -- and it means requesting a scan spanning (close to) the
axis' FULL real travel range, with padding enabled, will overshoot past
the real travel limits and fail scan_axis()'s pre-MOV range check (with a
clear error) rather than silently doing something unsafe.

The proven MATLAB code never solved this either: its own MOV() wrapper has
an identical hardware range check, so requesting a full-travel-range scan
with padding there would have failed the exact same way. The original lab
simply never did that, by manual convention -- there was no code-level
protection.

get_scan_safe_range(axis) (below) computes, in closed form, the largest
sub-range of an axis' real travel range that is guaranteed to remain
within real travel limits after padding is applied, for a scan spanning
up to that entire returned range (and, by direct consequence of the
overshoot scaling linearly with span, for any smaller scan positioned
anywhere inside that same returned range too). Solving
overshoot_per_side(R) == margin simultaneously with R == travel_span -
2*margin (i.e. a self-consistent "exactly uses up all its own margin"
scan) simplifies to:

    margin = travel_span * (1 - ratio) / 2

PIE710CounterInterfuse uses this (via getattr, since PIE710Scanner has no
padding concept and therefore no need for this method) to restrict the
scan-range GUI/constraints proactively, so this class of error should
never actually surface to a user in normal operation -- only
move_absolute()/get_position()/etc. (ordinary, non-scanning motion) still
use the full real x_range/y_range/z_range; only the scan-range
constraint is narrowed.

STILL NOT INDEPENDENTLY VERIFIED ON THIS SPECIFIC UNIT: the exact best
lin_pts_ratio value for this stage's mechanics. lin_pts_ratio=1.0 (no
padding at all) has been observed on real hardware to produce ZERO
trigger pulses for an entire line -- the real physical servo response
has inherent following error/lag right at motion start with no
acceleration runway at all, so the actual position may never cleanly
cross the trigger threshold. lin_pts_ratio=0.7 (the MATLAB default) was
observed to occasionally produce a small number of extra, decelerating-
pattern spurious edges before settling into clean triggering (traced to
the trigger-disable-ordering bug above, now fixed). lin_pts_ratio=0.5 has
been confirmed, after that fix, to produce exactly n_pixels + 1 real
trigger edges with a clean, uniform inter-trigger timing pattern on real
hardware. Treat 0.5 as the current known-good value for this stage;
revisit only if scans show visible distortion at line edges.

CRITICAL CROSS-FILE COUPLING -- RESOLVED
-------------------------------------------
An earlier version of this module's docstring warned that
NIXSeriesCounter's clock-based arm()/read() hardcodes a sample rate
(_PI_SAMP_RATE) that must match this controller's wave_generator_rate_hz.
That coupling does not apply when this scanner is used with
NIXSeriesCounter's arm_position_trigger()/read_position_trigger() methods
(selected via PIE710CounterInterfuse's counter_trigger_mode:
'position_distance' config option) -- that acquisition path has no
notion of a fixed scan clock rate at all; it hardware-counts real trigger
edges directly. Confirmed on real hardware for this E-727 (via
SPA? 1 0x0E000200 = 50 us servo cycle, WTR? = 1 cycle/point, and
independently confirmed by the proven MATLAB code's own SampRate = 20e3
property) that the true wave generator rate is 20000.0 Hz -- this value
matters for this module's own internal timing calculations
(wave_generator_rate_hz config option below) regardless of which counter
acquisition mode is used downstream.

YAML configuration:
    hardware:
        my_pi_e727_scanner:
            module.Class: 'hardware.pi_e727_scanning_probe.PIE727Scanner'
            options:
                dll_path:   'C:/Users/diamondx/Documents/PIDriverThings/API/PI_GCS2_DLL_x64.dll'
                usb_serial: ''
                axis_ids:   ['1', '2', '3']
                x_range: [0.0, 200.0]
                y_range: [0.0, 200.0]
                z_range: [0.0, 200.0]
                trigger_output_id: 1
                wave_generator_rate_hz: 20000.0   # confirmed -- see module docstring
                lin_pts_ratio: 0.5                # confirmed working on real hardware -- see module docstring
"""

import ctypes
import os
import threading
import time
from typing import Dict, List, Optional, Tuple

import numpy as np

from qudi.core.configoption import ConfigOption

# Reuses the SAME abstract interface as the E-710 module, so this class is
# a drop-in replacement behind the existing PIE710CounterInterfuse without
# any changes to that interfuse's Connector wiring. Adjust this import
# path to wherever pi_e710_scanning_probe.py actually lives in your
# project tree.
from .pi_e710_scanning_probe import PIE710ScannerInterface


# ══════════════════════════════════════════════════════════════════════════════
#  PI GCS2 DLL WRAPPER  (PI_GCS2_DLL_x64.dll)
#  All wave/trigger functions below use the COMPILED per-command DLL
#  functions, matching the confirmed real header (PI_GCS2_DLL.h) and the
#  proven MATLAB implementation -- NOT the generic ASCII string channel.
# ══════════════════════════════════════════════════════════════════════════════

class PIE727Error(Exception):
    def __init__(self, message: str, error_code: int = 0):
        super().__init__(message)
        self.error_code = error_code


class PIE727Controller:
    """
    ctypes wrapper for PI_GCS2_DLL_x64.dll, used with an E-727 digital
    piezo controller driving a P-562.3CD nanopositioning stage.

    See module docstring, "VERIFICATION STATUS", for what is confirmed
    against the real header vs. ported directly from the proven MATLAB
    implementation.
    """

    _SOFT_ERRORS = frozenset({0, 2, 5, 7, 8, 10})
    _BUF_SM = 256
    _BUF_MD = 1024

    def __init__(self, dll_path: str, use_windll: bool = False):
        self._id: int = -1
        self._dll_path = dll_path
        self._registered: set = set()
        self._axes: List[str] = []
        self._travel_min: List[float] = []
        self._travel_max: List[float] = []

        self.wave_generator_rate_hz: Optional[float] = None
        # Servo update period, seconds -- 1 / wave_generator_rate_hz, set
        # alongside it. Used for wave-timing calculations, matching the
        # proven MATLAB code's servo_pt_time property.
        self.servo_point_time_s: Optional[float] = None

        # Fraction of each line spent in the linear (triggered) region,
        # with the remainder split between speed-up/slow-down ramps on
        # each side. Matches the proven MATLAB code's lin_pts_ratio_1D.
        self.lin_pts_ratio: float = 1.0

        # Cached parameters from the most recent scan_axis() call, so
        # retrigger_line() can repeat the exact same line -- see module
        # docstring for why this must be a full repeat, not a bare WGO.
        self._last_scan_kwargs: Optional[dict] = None

        self._dll = self._load_dll(dll_path, use_windll)
        self._setup_signatures()

    @staticmethod
    def _load_dll(path: str, use_windll: bool) -> ctypes.CDLL:
        if not os.path.isfile(path):
            raise PIE727Error(f"DLL not found: '{path}'")
        try:
            return (ctypes.WinDLL if use_windll else ctypes.CDLL)(path)
        except OSError as exc:
            raise PIE727Error(f"Cannot load DLL: {exc}") from exc

    def _setup_signatures(self):
        d  = self._dll
        I  = ctypes.c_int
        D  = ctypes.c_double
        CP = ctypes.c_char_p
        PI = ctypes.POINTER(ctypes.c_int)
        PD = ctypes.POINTER(ctypes.c_double)
        CI = ctypes.c_int   # BOOL is a plain int on Windows

        def sig(name, rt, *at):
            try:
                fn = getattr(d, name)
                fn.restype = rt
                fn.argtypes = list(at)
                self._registered.add(name)
            except AttributeError:
                pass

        # ── Connection ────────────────────────────────────────────────────
        sig("PI_ConnectUSB",       I, CP)
        sig("PI_ConnectRS232",     I, I, I)
        sig("PI_IsConnected",      I, I)
        sig("PI_CloseConnection",  None, I)
        sig("PI_GetError",         I, I)
        sig("PI_TranslateError",   I, I, CP, I)

        # ── Identification ────────────────────────────────────────────────
        sig("PI_qIDN",   I, I, CP, I)
        sig("PI_qVER",   I, I, CP, I)
        # CONFIRMED against the real header: only 3 arguments, no filter
        # parameter.
        sig("PI_qSAI",   I, I, CP, I)

        # ── Servo / motion ────────────────────────────────────────────────
        sig("PI_SVO",       I, I, CP, PI)
        sig("PI_qSVO",      I, I, CP, PI)
        sig("PI_MOV",       I, I, CP, PD)
        sig("PI_MVR",       I, I, CP, PD)
        sig("PI_qPOS",      I, I, CP, PD)
        sig("PI_qONT",      I, I, CP, PI)
        sig("PI_IsMoving",  I, I, CP, PI)
        sig("PI_HLT",       I, I, CP)
        sig("PI_STP",       I, I)
        sig("PI_qTMN",      I, I, CP, PD)
        sig("PI_qTMX",      I, I, CP, PD)
        sig("PI_VEL",       I, I, CP, PD)
        sig("PI_qVEL",      I, I, CP, PD)

        # ── Digital I/O info (used only for diagnostics) ──────────────────
        sig("PI_qTIO", I, I, PI, PI)

        # ── Wave generator (compiled functions, confirmed real signatures) ─
        sig("PI_IsGeneratorRunning", I, I, PI, PI, I)
        sig("PI_WAV_LIN", I, I, I, I, I, I, I, D, D, I)
        sig("PI_qWAV",    I, I, PI, PI, PD, I)
        sig("PI_WGO",     I, I, PI, PI, I)
        sig("PI_qWGO",    I, I, PI, PI, I)
        sig("PI_WGC",     I, I, PI, PI, I)
        sig("PI_WSL",     I, I, PI, PI, I)
        sig("PI_WCL",     I, I, PI, I)
        sig("PI_WOS",     I, I, PI, PD, I)

        # ── Trigger output (compiled functions) ───────────────────────────
        sig("PI_CTO",  I, I, PI, PI, PD, I)
        sig("PI_qCTO", I, I, PI, PI, PD, I)

    def _fn(self, name: str):
        if name not in self._registered:
            raise PIE727Error(
                f"'{name}' not exported by '{os.path.basename(self._dll_path)}'")
        return getattr(self._dll, name)

    def _require_connection(self):
        if self._id < 0:
            raise PIE727Error("Not connected.")

    def _check(self, result: int, fname: str):
        if not result:
            code = self._dll.PI_GetError(self._id) if self._id >= 0 else -1
            raise PIE727Error(
                f"'{fname}' failed -- error {code}: {self._translate(code)}", code)

    def _soft_check(self, result: int, fname: str) -> bool:
        if result:
            return True
        code = self._dll.PI_GetError(self._id) if self._id >= 0 else -1
        if code in self._SOFT_ERRORS:
            return False
        raise PIE727Error(
            f"'{fname}' failed -- error {code}: {self._translate(code)}", code)

    def _translate(self, code: int) -> str:
        if "PI_TranslateError" not in self._registered:
            return f"(PI_TranslateError not exported -- code {code} untranslated)"
        buf = ctypes.create_string_buffer(self._BUF_MD)
        try:
            self._fn("PI_TranslateError")(code, buf, self._BUF_MD)
        except Exception as exc:
            return f"(translation call failed for code {code}: {exc})"
        return buf.value.decode("ascii", errors="replace").strip()

    @staticmethod
    def _ax(axes) -> bytes:
        if isinstance(axes, bytes):
            return axes
        if isinstance(axes, (list, tuple)):
            return " ".join(str(a) for a in axes).encode("ascii")
        if isinstance(axes, str):
            return axes.encode("ascii")
        return b""

    @staticmethod
    def _nax(axes, fallback: int = 0) -> int:
        if isinstance(axes, (list, tuple)):
            return len(axes)
        b = PIE727Controller._ax(axes)
        return len(b.split()) if b else fallback

    @staticmethod
    def _darr(vals) -> ctypes.Array:
        v = list(vals)
        return (ctypes.c_double * len(v))(*v)

    @staticmethod
    def _iarr(vals) -> ctypes.Array:
        v = [int(x) for x in vals]
        return (ctypes.c_int * len(v))(*v)

    def _dbuf(self, n: int) -> ctypes.Array:
        return (ctypes.c_double * max(n, 1))()

    def _ibuf(self, n: int) -> ctypes.Array:
        return (ctypes.c_int * max(n, 1))()

    def clear_error(self):
        if self._id >= 0:
            self._dll.PI_GetError(self._id)

    # ── Properties ────────────────────────────────────────────────────────────

    @property
    def connected(self) -> bool:
        return self._id >= 0 and bool(self._dll.PI_IsConnected(self._id))

    @property
    def axes(self) -> List[str]:
        return list(self._axes)

    @property
    def travel_min(self) -> List[float]:
        return list(self._travel_min)

    @property
    def travel_max(self) -> List[float]:
        return list(self._travel_max)

    # ── Connection ────────────────────────────────────────────────────────────

    def connect_usb(self, description: str = "") -> int:
        _id = self._fn("PI_ConnectUSB")(description.encode("ascii"))
        if _id < 0:
            raise PIE727Error(f"USB connect failed (description='{description}')")
        self._id = _id
        return _id

    def connect_rs232(self, port_number: int, baud_rate: int = 115200) -> int:
        _id = self._fn("PI_ConnectRS232")(port_number, baud_rate)
        if _id < 0:
            raise PIE727Error(f"RS-232 connect failed (COM{port_number})")
        self._id = _id
        return _id

    def close_connection(self):
        if self._id >= 0:
            try:
                self._fn("PI_CloseConnection")(self._id)
            except Exception:
                pass
            self._id = -1

    # ── Identification ────────────────────────────────────────────────────────

    def get_identification(self) -> str:
        self._require_connection()
        buf = ctypes.create_string_buffer(self._BUF_MD)
        self._check(self._fn("PI_qIDN")(self._id, buf, self._BUF_MD), "qIDN")
        return buf.value.decode("ascii", errors="replace").strip()

    def get_version(self) -> str:
        self._require_connection()
        buf = ctypes.create_string_buffer(self._BUF_MD)
        ok = self._soft_check(
            self._fn("PI_qVER")(self._id, buf, self._BUF_MD), "qVER")
        return (buf.value.decode("ascii", errors="replace").strip()
                if ok else "(not supported)")

    def get_axes(self) -> List[str]:
        self._require_connection()
        buf = ctypes.create_string_buffer(self._BUF_MD)
        ok = self._soft_check(
            self._fn("PI_qSAI")(self._id, buf, self._BUF_MD), "qSAI")
        if not ok:
            return ['1', '2', '3']
        raw = buf.value.decode("ascii", errors="replace").strip()
        axes = [line.strip() for line in raw.splitlines() if line.strip()]
        return axes if axes else ['1', '2', '3']

    def get_digital_io_counts(self) -> Tuple[int, int]:
        """Diagnostic only: number of digital input/output lines (TIO?)."""
        self._require_connection()
        n_in, n_out = ctypes.c_int(0), ctypes.c_int(0)
        self._check(
            self._fn("PI_qTIO")(self._id, ctypes.byref(n_in), ctypes.byref(n_out)),
            "qTIO")
        return n_in.value, n_out.value

    # ── Servo ─────────────────────────────────────────────────────────────────

    def set_servo(self, axes, states: List[bool]):
        self._require_connection()
        self._check(
            self._fn("PI_SVO")(self._id, self._ax(axes), self._iarr(states)),
            "SVO")

    def get_servo(self, axes) -> List[bool]:
        self._require_connection()
        n = self._nax(axes, len(self._axes))
        arr = self._ibuf(n)
        self._check(self._fn("PI_qSVO")(self._id, self._ax(axes), arr), "qSVO")
        return [bool(arr[i]) for i in range(n)]

    # ── Motion ────────────────────────────────────────────────────────────────

    def get_position(self, axes) -> List[float]:
        self._require_connection()
        n = self._nax(axes, len(self._axes))
        arr = self._dbuf(n)
        self._check(self._fn("PI_qPOS")(self._id, self._ax(axes), arr), "qPOS")
        return [arr[i] for i in range(n)]

    def move_absolute(self, axes, positions: List[float]):
        self._require_connection()
        self._check(
            self._fn("PI_MOV")(self._id, self._ax(axes), self._darr(positions)),
            "MOV")

    def move_relative(self, axes, steps: List[float]):
        self._require_connection()
        self._check(
            self._fn("PI_MVR")(self._id, self._ax(axes), self._darr(steps)),
            "MVR")

    def is_moving(self, axes) -> List[bool]:
        self._require_connection()
        n = self._nax(axes, len(self._axes))
        arr = self._ibuf(n)
        self._check(
            self._fn("PI_IsMoving")(self._id, self._ax(axes), arr), "IsMoving")
        return [bool(arr[i]) for i in range(n)]

    def is_on_target(self, axes) -> List[bool]:
        self._require_connection()
        n = self._nax(axes, len(self._axes))
        arr = self._ibuf(n)
        self._check(
            self._fn("PI_qONT")(self._id, self._ax(axes), arr), "qONT")
        return [bool(arr[i]) for i in range(n)]

    def halt(self, axes):
        self._require_connection()
        self._check(self._fn("PI_HLT")(self._id, self._ax(axes)), "HLT")

    def stop_all(self):
        self._require_connection()
        self._check(self._fn("PI_STP")(self._id), "STP")

    def wait_for_motion(
        self, axes, poll_interval: float = 0.05,
        timeout: float = 60.0, settle_check: bool = True,
    ):
        deadline = time.monotonic() + timeout
        while any(self.is_moving(axes)):
            if time.monotonic() > deadline:
                raise PIE727Error(f"Timeout waiting for motion on '{axes}'")
            time.sleep(poll_interval)
        if settle_check:
            settle_deadline = time.monotonic() + min(timeout * 0.25, 5.0)
            while not all(self.is_on_target(axes)):
                if time.monotonic() > settle_deadline:
                    break
                time.sleep(poll_interval)

    # ── Travel limits / velocity ──────────────────────────────────────────────

    def get_min_travel(self, axes) -> List[float]:
        self._require_connection()
        n = self._nax(axes, len(self._axes))
        arr = self._dbuf(n)
        self._check(self._fn("PI_qTMN")(self._id, self._ax(axes), arr), "qTMN")
        return [arr[i] for i in range(n)]

    def get_max_travel(self, axes) -> List[float]:
        self._require_connection()
        n = self._nax(axes, len(self._axes))
        arr = self._dbuf(n)
        self._check(self._fn("PI_qTMX")(self._id, self._ax(axes), arr), "qTMX")
        return [arr[i] for i in range(n)]

    def set_velocity(self, axes, velocities: List[float]):
        self._require_connection()
        self._check(
            self._fn("PI_VEL")(self._id, self._ax(axes), self._darr(velocities)),
            "VEL")

    # ── Wave generator (compiled functions) ──────────────────────────────────

    def wave_clear(self, wave_table_ids: List[int]):
        self._require_connection()
        arr = self._iarr(wave_table_ids)
        self._check(
            self._fn("PI_WCL")(self._id, arr, len(wave_table_ids)), "WCL")

    def wave_lin(
        self, wave_table_id: int, offset_first_point: int,
        n_points: int, add_append_wave: int,
        n_speedupdown_points: int, amplitude: float, offset: float,
        segment_length: int,
    ):
        """
        PI_WAV_LIN(ID, iWaveTableId, iOffsetOfFirstPointInWaveTable,
        iNumberOfPoints, iAddAppendWave, iNumberOfSpeedUpDownPointsInWave,
        dAmplitudeOfWave, dOffsetOfWave, iSegmentLength)

        add_append_wave: 0 = new/replace table content, 2 = append
        (matches the proven MATLAB usage pattern -- confirmed against the
        real compiled function signature, not the ASCII 'X'/'&' string
        convention used only by the separate GCS-string WAV command).
        """
        self._require_connection()
        self._check(
            self._fn("PI_WAV_LIN")(
                self._id, wave_table_id, offset_first_point, n_points,
                add_append_wave, n_speedupdown_points,
                ctypes.c_double(amplitude), ctypes.c_double(offset),
                segment_length),
            "WAV_LIN")

    def wave_select(self, wave_gen_ids: List[int], wave_table_ids: List[int]):
        self._require_connection()
        assert len(wave_gen_ids) == len(wave_table_ids)
        self._check(
            self._fn("PI_WSL")(
                self._id, self._iarr(wave_gen_ids), self._iarr(wave_table_ids),
                len(wave_gen_ids)),
            "WSL")

    def wave_set_cycles(self, wave_gen_ids: List[int], cycles: List[int]):
        self._require_connection()
        assert len(wave_gen_ids) == len(cycles)
        self._check(
            self._fn("PI_WGC")(
                self._id, self._iarr(wave_gen_ids), self._iarr(cycles),
                len(wave_gen_ids)),
            "WGC")

    def wave_set_offset(self, wave_gen_ids: List[int], offsets: List[float]):
        self._require_connection()
        assert len(wave_gen_ids) == len(offsets)
        self._check(
            self._fn("PI_WOS")(
                self._id, self._iarr(wave_gen_ids), self._darr(offsets),
                len(wave_gen_ids)),
            "WOS")

    def wave_start_stop(self, wave_gen_ids: List[int], start_modes: List[int]):
        """
        PI_WGO(ID, piWaveGeneratorIdsArray, iStartModArray, iArraySize).
        start_modes: 1 = start ("immediately", bit 0), 0 = stop.
        """
        self._require_connection()
        assert len(wave_gen_ids) == len(start_modes)
        self._check(
            self._fn("PI_WGO")(
                self._id, self._iarr(wave_gen_ids), self._iarr(start_modes),
                len(wave_gen_ids)),
            "WGO")

    def is_wave_generator_running(self, wave_gen_ids: List[int]) -> List[bool]:
        self._require_connection()
        arr = self._iarr(wave_gen_ids)
        out = self._ibuf(len(wave_gen_ids))
        self._check(
            self._fn("PI_IsGeneratorRunning")(
                self._id, arr, out, len(wave_gen_ids)),
            "IsGeneratorRunning")
        return [bool(out[i]) for i in range(len(wave_gen_ids))]

    # ── Trigger output (compiled function, position-distance mode) ──────────

    def set_trigger_param(self, trig_out_id: int, cto_param: int, value: float):
        """
        Single PI_CTO(ID, [trig_out_id], [cto_param], [value], 1) call --
        one (TrigOutID, CTOPam, Value) triple at a time, matching the
        proven MATLAB code's own call-by-call style (easier to isolate a
        failure to one specific parameter than a combined multi-entry
        call).
        """
        self._require_connection()
        self._check(
            self._fn("PI_CTO")(
                self._id,
                self._iarr([trig_out_id]),
                self._iarr([cto_param]),
                self._darr([value]),
                1),
            f"CTO (param={cto_param}, value={value})")

    def get_trigger_param(self, trig_out_id: int, cto_param: int) -> float:
        self._require_connection()
        out = self._dbuf(1)
        self._check(
            self._fn("PI_qCTO")(
                self._id, self._iarr([trig_out_id]), self._iarr([cto_param]),
                out, 1),
            "qCTO")
        return out[0]

    def configure_position_distance_trigger(
        self, trigger_output_id: int, axis_num: int,
        trig_step: float, trig_start: float, trig_stop: float,
        disable_threshold: float,
    ):
        """
        Configure trigger_output_id for GCS TriggerMode 0 ("Position
        Distance"): one physical trigger pulse per trig_step of real
        motion along axis_num, only while position is within
        [trig_start, trig_stop]. Ported directly from the proven MATLAB
        ScanLine sequence (CTO calls in that exact order):

            1. CTO(trig_out, 8, disable_threshold)  -- disable triggering
               first, by setting the start threshold far outside any
               real travel range, so no stray triggers fire while the
               remaining parameters are still being set up.
            2. CTO(trig_out, 2, axis_num)  -- select the trigger axis
            3. CTO(trig_out, 3, 0)         -- TriggerMode 0 = Position Distance
            4. CTO(trig_out, 1, trig_step) -- step size
            5. CTO(trig_out, 8, trig_start) -- real start threshold
            6. CTO(trig_out, 9, trig_stop)  -- real stop threshold
        """
        self.set_trigger_param(trigger_output_id, 8, disable_threshold)
        self.set_trigger_param(trigger_output_id, 2, axis_num)
        self.set_trigger_param(trigger_output_id, 3, 0)
        self.set_trigger_param(trigger_output_id, 1, trig_step)
        self.set_trigger_param(trigger_output_id, 8, trig_start)
        self.set_trigger_param(trigger_output_id, 9, trig_stop)

    # ── High-level single-axis line scan (ported from proven MATLAB ScanLine) ─

    def scan_axis(
        self, axis_num: int, positions, t_pixel: float,
        trigger_output_id: int, wave_generator_rate_hz: float,
        disable_threshold: float,
    ) -> float:
        """
        Configure and run a single-axis line scan. See module docstring
        for the full description of the ported MATLAB algorithm.

        lin_pts_ratio == 1.0: padding/speed-up-slow-down is OFF entirely.
        The wave ramps directly across [start, stop] with no overshoot
        outside the requested range, and no gentle acceleration region.
        Observed on real hardware to sometimes produce ZERO real trigger
        edges for a whole line -- see module docstring, "STILL NOT
        INDEPENDENTLY VERIFIED" -- prefer lin_pts_ratio < 1.0 in practice.

        lin_pts_ratio < 1.0: speed-up/slow-down padding is enabled, per
        the proven MATLAB algorithm. See module docstring, "SCAN RANGE VS.
        lin_pts_ratio PADDING", for the exact overshoot formula and how
        get_scan_safe_range() uses it to keep the GUI from ever selecting
        a range that would trip the check below.
        """
        self._require_connection()
        n_points = len(positions)
        start, stop = positions[0], positions[-1]
        amp_true = stop - start

        ratio = self.lin_pts_ratio
        servo_pt = 1.0 / wave_generator_rate_hz
        line_time = t_pixel * n_points / min(ratio, 1.0)

        if ratio >= 1.0:
            # Padding OFF: scan exactly [start, stop], no overshoot, no
            # speed-up/slow-down region at all.
            wave_offset = start
            amp_padded = amp_true
            n_speedupdown = 0
            linear_region_len = round(line_time / servo_pt)
        else:
            perc_over = ratio / ((1.0 - ratio) / 2.0)
            wave_offset = start - amp_true / perc_over
            amp_padded = amp_true / ratio
            linear_region_len = round(line_time * ratio / servo_pt)
            n_speedupdown = round(line_time * (1.0 - ratio) / servo_pt / 2.0)

        n_wave_points = linear_region_len + 2 * n_speedupdown
        segment_length = n_wave_points

        travel_min = self.get_min_travel([str(axis_num)])[0]
        travel_max = self.get_max_travel([str(axis_num)])[0]
        padded_low  = wave_offset
        padded_high = wave_offset + amp_padded
        # Tolerance clears IEEE double-precision rounding noise in the
        # padding arithmetic above (e.g. start - amp_true/perc_over can
        # land on -1e-14 instead of exactly 0.0 for a scan request that
        # is, geometrically, exactly on the travel boundary) -- 1e-6 um
        # (1 pm) is far below any real mechanical/positioning precision
        # of this stage, so this never masks a genuine out-of-range
        # request, only float noise around an exact boundary.
        _tol = 1e-6
        if padded_low < travel_min - _tol or padded_high > travel_max + _tol:
            raise PIE727Error(
                f"scan_axis: padded scan range [{padded_low:.4f}, "
                f"{padded_high:.4f}] um (requested [{start:.4f}, "
                f"{stop:.4f}] um"
                + ("" if ratio >= 1.0 else
                   f" + speed-up/slow-down padding via lin_pts_ratio={ratio}")
                + f") exceeds axis {axis_num}'s real travel range "
                f"[{travel_min:.4f}, {travel_max:.4f}] um."
            )

        # The tolerance above only gates the sanity CHECK -- it does not
        # change the value actually sent to move_absolute()/wave_lin().
        # Real PI firmware enforces its travel limit with zero tolerance
        # of its own, so a wave_offset that is float noise away from an
        # exact boundary (e.g. -1.4e-7 instead of exactly 0.0) would pass
        # the check above but still get rejected by real hardware at MOV
        # time ('error 7: Position out of limits'). Clamping here, AFTER
        # the sanity check, is what actually fixes that -- the check
        # above still catches genuinely out-of-range requests; this only
        # snaps float noise back onto the real boundary for values that
        # already passed it.
        wave_offset = float(np.clip(wave_offset, travel_min, travel_max))

        # Disable triggering BEFORE moving to the new line's wave_offset --
        # matches the proven MATLAB ScanLine's ordering (CTO disable is
        # its very first trigger-related call, issued before MOV). See
        # module docstring, item 4, for why issuing the move first (an
        # earlier version of this method's ordering) is a real bug: it
        # leaves the PREVIOUS line's trigger thresholds fully armed while
        # this move travels through a wide range of real positions,
        # generating real, physical extra trigger pulses that get counted
        # as if they belonged to the next line.
        self.set_trigger_param(trigger_output_id, 8, disable_threshold)

        self.move_absolute([str(axis_num)], [wave_offset])
        self.wait_for_motion([str(axis_num)], timeout=30.0)

        self.wave_clear([axis_num])
        self.wave_set_cycles([axis_num], [1])
        self.wave_lin(
            wave_table_id=axis_num, offset_first_point=0,
            n_points=n_wave_points, add_append_wave=0,
            n_speedupdown_points=n_speedupdown,
            amplitude=amp_padded, offset=wave_offset,
            segment_length=segment_length,
        )
        self.wave_select([axis_num], [axis_num])

        trig_step = amp_true / n_points
        trig_start = start
        trig_stop = trig_start + amp_true + trig_step * 0.5
        self.configure_position_distance_trigger(
            trigger_output_id=trigger_output_id, axis_num=axis_num,
            trig_step=trig_step, trig_start=trig_start, trig_stop=trig_stop,
            disable_threshold=disable_threshold,
        )

        self.wave_set_offset([axis_num], [0.0])
        self.wave_start_stop([axis_num], [1])

        return segment_length * servo_pt * 1.1

    def retrigger_line(self) -> float:
        """
        Re-run the most recently configured line scan from scratch. This
        CANNOT be a bare WGO restart -- see module docstring for why the
        proven hardware/algorithm leaves the stage at the END of the
        ramp, not the start, after every line, so a genuine repeat needs
        the full move + reprogram + retrigger sequence, exactly like the
        first line.
        """
        if self._last_scan_kwargs is None:
            raise PIE727Error(
                "retrigger_line() called with no prior scan_axis() call.")
        return self.scan_axis(**self._last_scan_kwargs)

    # ── Context manager ───────────────────────────────────────────────────────

    def __enter__(self):
        return self

    def __exit__(self, *_):
        self.close_connection()

    def __del__(self):
        try:
            self.close_connection()
        except Exception:
            pass


# ══════════════════════════════════════════════════════════════════════════════
#  CONCRETE HARDWARE MODULE — PIE727Scanner
# ══════════════════════════════════════════════════════════════════════════════

class PIE727Scanner(PIE710ScannerInterface):
    """
    PI E-727 + P-562.3CD Qudi hardware module — motion and waveform
    control only. Drop-in replacement for PIE710Scanner behind
    PIE710CounterInterfuse.

    See module docstring, "VERIFICATION STATUS", before trusting scan
    timing/trigger behavior further on real hardware.
    """

    _dll_path            = ConfigOption('dll_path', default="C:/PI/PI_GCS2_DLL_x64.dll")
    _usb_serial           = ConfigOption('usb_serial', default="")
    _axis_ids             = ConfigOption('axis_ids', default=['1', '2', '3'])
    _x_range              = ConfigOption('x_range', default=[0.0, 200.0])
    _y_range              = ConfigOption('y_range', default=[0.0, 200.0])
    _z_range              = ConfigOption('z_range', default=[0.0, 200.0])
    _trigger_output_id    = ConfigOption('trigger_output_id', default=1)
    _wave_generator_rate_hz = ConfigOption('wave_generator_rate_hz', default=20000.0)
    _lin_pts_ratio        = ConfigOption('lin_pts_ratio', default=1.0)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._ctrl: Optional[PIE727Controller] = None
        self._target_pos: Dict[str, float] = {'x': 0.0, 'y': 0.0, 'z': 0.0}
        self._axis_of: Dict[str, str] = {}
        self._active_scan_axis: Optional[str] = None

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    def on_activate(self) -> None:
        self._ctrl = None
        try:
            self._ctrl = PIE727Controller(self._dll_path)
            self._ctrl.connect_usb(self._usb_serial)

            ids = list(self._axis_ids)
            if len(ids) < 3:
                raise PIE727Error(
                    f"axis_ids config must have 3 entries (x,y,z); got {ids}")
            self._axis_of = {'x': ids[0], 'y': ids[1], 'z': ids[2]}
            self._ctrl._axes = ids

            idn = self._ctrl.get_identification()
            self.log.info(f"PI E-727 connected: {idn}")

            self._ctrl.set_servo(ids, [True, True, True])
            time.sleep(0.1)

            mn = self._ctrl.get_min_travel(ids)
            mx = self._ctrl.get_max_travel(ids)
            self.log.info(
                f"Travel limits (from hardware): "
                f"{ids[0]}:[{mn[0]:.3f},{mx[0]:.3f}]  "
                f"{ids[1]}:[{mn[1]:.3f},{mx[1]:.3f}]  "
                f"{ids[2]}:[{mn[2]:.3f},{mx[2]:.3f}] um"
            )
            self._x_range = [mn[0], mx[0]]
            self._y_range = [mn[1], mx[1]]
            self._z_range = [mn[2], mx[2]]

            pos = self._ctrl.get_position(ids)
            self._target_pos = {'x': pos[0], 'y': pos[1], 'z': pos[2]}
            self.log.info(
                f"Position  x={pos[0]:.3f}  y={pos[1]:.3f}  z={pos[2]:.3f} um"
            )

            self._ctrl.wave_generator_rate_hz = float(self._wave_generator_rate_hz)
            self._ctrl.servo_point_time_s = 1.0 / float(self._wave_generator_rate_hz)
            self._ctrl.lin_pts_ratio = float(self._lin_pts_ratio)

            # Log scan-safe ranges alongside real travel limits, so it's
            # visible at activation time whether/how much the GUI's scan
            # range will be narrowed by the current lin_pts_ratio -- see
            # module docstring, "SCAN RANGE VS. lin_pts_ratio PADDING".
            for ax in ('x', 'y', 'z'):
                full = {'x': self._x_range, 'y': self._y_range, 'z': self._z_range}[ax]
                safe = self.get_scan_safe_range(ax)
                self.log.info(
                    f"Axis '{ax}' scan-safe range (lin_pts_ratio="
                    f"{self._lin_pts_ratio}): [{safe[0]:.3f}, {safe[1]:.3f}] um  "
                    f"(real travel: [{full[0]:.3f}, {full[1]:.3f}] um)"
                )
        except Exception as exc:
            # Prevent a leaked/half-open USB connection on any activation
            # failure -- do NOT rely on __del__/garbage collection timing
            # to close it. Confirmed real issue: the E-727/DLL combination
            # is documented (in the working MATLAB driver's own comments)
            # to sometimes accept multiple simultaneous connections rather
            # than cleanly rejecting a second one, which can corrupt
            # subsequent responses on ANY of the open connections.
            if self._ctrl is not None:
                try:
                    self._ctrl.close_connection()
                except Exception:
                    pass
                self._ctrl = None
            self.log.exception(f"PI E-727 activation failed: {exc}")
            raise

    def on_deactivate(self) -> None:
        if self._ctrl is not None:
            try:
                self._ctrl.close_connection()
            except Exception as exc:
                self.log.warning(f"PI close_connection: {exc}")
            self._ctrl = None

    # ── Range properties (real hardware travel limits) ────────────────────────

    @property
    def x_range(self) -> List[float]:
        return list(self._x_range)

    @property
    def y_range(self) -> List[float]:
        return list(self._y_range)

    @property
    def z_range(self) -> List[float]:
        return list(self._z_range)

    # ── Scan-safe range (padding-aware) ────────────────────────────────────────

    def _scan_safe_margin(self, travel_min: float, travel_max: float) -> float:
        """
        See module docstring, "SCAN RANGE VS. lin_pts_ratio PADDING", for
        the derivation. margin = travel_span * (1 - ratio) / 2.
        """
        ratio = float(self._lin_pts_ratio)
        if ratio >= 1.0:
            return 0.0
        return (travel_max - travel_min) * (1.0 - ratio) / 2.0

    def get_scan_safe_range(self, axis: str) -> List[float]:
        """
        Returns the sub-range of this axis' real travel range that is
        guaranteed to remain within real travel limits after scan_axis()
        applies lin_pts_ratio padding, for a scan spanning up to this
        entire returned range (and, by direct consequence of the
        overshoot scaling linearly with span, for any smaller scan
        positioned anywhere inside this same returned range too).

        Used by PIE710CounterInterfuse, via getattr() (since
        PIE710Scanner has no padding concept and therefore no need for
        this method), to restrict the scan-range GUI/constraints to
        values that will not raise scan_axis()'s travel-range error at
        scan time.

        Does NOT affect move_absolute()/get_position()/etc. -- ordinary,
        non-scanning motion is still clipped against the full real
        x_range/y_range/z_range; only the scan-range constraint reported
        to the interfuse is narrowed.

        Rounded to 6 decimal places (nanometer-level for um values) to
        clear IEEE double-precision rounding noise in the margin
        calculation (e.g. 1.0 - 0.7 is not exactly 0.3 in floating point)
        -- without this, a GUI-entered boundary value exactly equal to
        the intended bound (e.g. 30.0 for a computed margin that should
        be exactly 30.0) could be rejected by ScalarConstraint.check() as
        "out of bounds" against a noisy bound like 30.000000000000004.
        """
        full = {'x': self._x_range, 'y': self._y_range, 'z': self._z_range}[axis]
        lo, hi = full
        margin = self._scan_safe_margin(lo, hi)
        return [round(lo + margin, 6), round(hi - margin, 6)]

    # ── Motion ────────────────────────────────────────────────────────────────

    def move_absolute(
        self, position: Dict[str, float], blocking: bool = False,
    ) -> Dict[str, float]:
        target = dict(self._target_pos)
        for ax, val in position.items():
            if ax in ('x', 'y', 'z'):
                target[ax] = float(val)
        target['x'] = float(np.clip(target['x'], *self._x_range))
        target['y'] = float(np.clip(target['y'], *self._y_range))
        target['z'] = float(np.clip(target['z'], *self._z_range))

        ids = [self._axis_of['x'], self._axis_of['y'], self._axis_of['z']]
        self._ctrl.move_absolute(ids, [target['x'], target['y'], target['z']])
        self._target_pos = target
        if blocking:
            self._ctrl.wait_for_motion(ids, timeout=60.0)
        return dict(self._target_pos)

    def move_relative(
        self, distance: Dict[str, float], blocking: bool = False,
    ) -> Dict[str, float]:
        current = self.get_target()
        new_pos = {ax: current[ax] + distance.get(ax, 0.0) for ax in ('x', 'y', 'z')}
        return self.move_absolute(new_pos, blocking=blocking)

    def get_target(self) -> Dict[str, float]:
        return dict(self._target_pos)

    def get_position(self) -> Dict[str, float]:
        try:
            ids = [self._axis_of['x'], self._axis_of['y'], self._axis_of['z']]
            pos = self._ctrl.get_position(ids)
            return {'x': pos[0], 'y': pos[1], 'z': pos[2]}
        except PIE727Error:
            return dict(self._target_pos)

    def sync_position(self) -> None:
        try:
            ids = [self._axis_of['x'], self._axis_of['y'], self._axis_of['z']]
            pos = self._ctrl.get_position(ids)
            self._target_pos = {'x': pos[0], 'y': pos[1], 'z': pos[2]}
        except PIE727Error as exc:
            self.log.warning(f"sync_position failed: {exc}")

    def halt(self) -> None:
        try:
            ids = [self._axis_of['x'], self._axis_of['y'], self._axis_of['z']]
            self._ctrl.halt(ids)
        except PIE727Error:
            pass

    def halt_generators(self) -> None:
        if self._active_scan_axis is not None:
            try:
                axis_num = int(self._axis_of[self._active_scan_axis])
                self._ctrl.wave_start_stop([axis_num], [0])
            except Exception:
                pass

    def reset(self) -> None:
        try:
            ids = [self._axis_of['x'], self._axis_of['y'], self._axis_of['z']]
            self._ctrl.set_servo(ids, [True, True, True])
            self.log.info("PI E-727 reset complete.")
        except PIE727Error as exc:
            self.log.error(f"PI E-727 reset failed: {exc}")

    # ── Scan commands ─────────────────────────────────────────────────────────

    def start_scan(
        self,
        axes:        Tuple[str, ...],
        positions:   Tuple[List[float], ...],
        t_pixel:     float,
        current_pos: Dict[str, float],
    ) -> float:
        if len(axes) != 1:
            raise NotImplementedError(
                "PIE727Scanner currently implements single-axis (1D fast-"
                "axis) line scans only. For 2D scanning, the interfuse's "
                "own line-by-line-via-retrigger_line() mechanism already "
                "covers this via repeated calls to this method + "
                "retrigger_line() per line."
            )

        axis = axes[0]
        axis_num = int(self._axis_of[axis])
        pos_array = positions[0]
        disable_threshold = max(self._x_range[1], self._y_range[1], self._z_range[1]) + 1.0

        scan_kwargs = dict(
            axis_num=axis_num, positions=pos_array, t_pixel=t_pixel,
            trigger_output_id=self._trigger_output_id,
            wave_generator_rate_hz=self._wave_generator_rate_hz,
            disable_threshold=disable_threshold,
        )
        duration_s = self._ctrl.scan_axis(**scan_kwargs)
        self._ctrl._last_scan_kwargs = scan_kwargs
        self._active_scan_axis = axis

        # NOTE: per module docstring, the stage is left at the END of the
        # ramp after the scan completes, NOT back at pos_array[0] -- do
        # NOT assume _target_pos == pos_array[0] here.
        self._target_pos[axis] = pos_array[-1]

        return duration_s

    def retrigger_line(self) -> float:
        duration_s = self._ctrl.retrigger_line()
        if self._active_scan_axis is not None:
            positions = self._ctrl._last_scan_kwargs['positions']
            self._target_pos[self._active_scan_axis] = positions[-1]
        return duration_s

    def wait_for_scan_complete(
        self,
        estimated_s:   float,
        stop_event:    Optional[threading.Event] = None,
        poll_interval: float = 0.25,
    ) -> bool:
        coarse_s = max(0.0, estimated_s * 0.80 - poll_interval)
        deadline = time.monotonic() + estimated_s * 3.0 + 10.0

        elapsed, chunk = 0.0, 0.1
        while elapsed < coarse_s:
            if stop_event and stop_event.is_set():
                return False
            time.sleep(chunk)
            elapsed += chunk

        axis_num = int(self._axis_of[self._active_scan_axis]) if self._active_scan_axis else None
        try:
            while time.monotonic() < deadline:
                if stop_event and stop_event.is_set():
                    return False
                if axis_num is not None and not self._ctrl.is_wave_generator_running([axis_num])[0]:
                    break
                time.sleep(poll_interval)
            else:
                self.log.warning("Scan completion timeout exceeded.")
        except Exception as exc:
            self.log.warning(f"Wave generator poll failed ({exc}); time-based fallback.")
            time.sleep(max(0.0, estimated_s - elapsed))

        # Per module docstring: the generator does NOT stop itself --
        # explicitly stop it now that the scan is done.
        if axis_num is not None:
            try:
                self._ctrl.wave_start_stop([axis_num], [0])
            except Exception as exc:
                self.log.warning(f"Failed to explicitly stop wave generator: {exc}")

        return True